### ISSUE TITLE
Does it work with H96 max rk3318 ?

### ISSUE THREAD

**Issue by peratik** [833M0L3/H96MaxX3#3]
Hi

Does it work with H96 max rk3318 ?

Best

**Comment by 833M0L3** [comment]
This tutorial is specifically for H96 MAX S905x3. There are boxes with rk3318 supporting armbian but I think in the end it all comes down to the dtb file. You have to either make it yourself or look for other pros who have the same device and ask them to make it for you.

But, instead of here, do go to this repository https://github.com/ophub/amlogic-s9xxx-armbian and open an issue there, as they are the developer of this project. I am just using their build and made this tutorial to help others with the installation.
